//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParentalControl.Web.Mvc.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevicePhone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DevicePhone()
        {
            this.App = new HashSet<App>();
            this.AppDevice = new HashSet<AppDevice>();
            this.DevicePhoneUse = new HashSet<DevicePhoneUse>();
        }
    
        public int DevicePhoneId { get; set; }
        public string DevicePhoneName { get; set; }
        public string DevicePhoneCode { get; set; }
        public System.DateTime DevicePhoneCreationDate { get; set; }
        public Nullable<int> InfantAccountId { get; set; }
        public int ParentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<App> App { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppDevice> AppDevice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevicePhoneUse> DevicePhoneUse { get; set; }
        public virtual InfantAccount InfantAccount { get; set; }
        public virtual Parent Parent { get; set; }
    }
}
