//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParentalControl.Web.Mvc.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceUse
    {
        public int DeviceUseId { get; set; }
        public string DeviceUseDay { get; set; }
        public System.DateTime DeviceUseCreationDate { get; set; }
        public int InfantAccountId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
    
        public virtual InfantAccount InfantAccount { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
