//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParentalControl.Web.Mvc.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WindowsAccount
    {
        public int WindowsAccountId { get; set; }
        public string WindowsAccountName { get; set; }
        public System.DateTime WindowsAccountCreationDate { get; set; }
        public int DevicePCId { get; set; }
        public int InfantAccountId { get; set; }
    
        public virtual DevicePC DevicePC { get; set; }
        public virtual InfantAccount InfantAccount { get; set; }
    }
}
